version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=blueprints
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - postgres-db:/var/lib/postgresql/data/

volumes:
  postgres-db:
    driver: local